---
title: "Untitled"
output: pdf_document
date: "2023-04-25"
---

```{r include=FALSE}
# Install and load the ggcorrplot and ggplot2 packages
library(ggcorrplot)
library(ggplot2)

# Install and load the caret package
library(caret)

library(readr)
# Install and load the mice package
library(mice)

library(dplyr)

library(corrplot)
```


```{r include=FALSE}
crime_data <- read_delim("communities.data", delim = ",")
column_names <- c("state", "county", "community", "communityname", "fold", "population", "householdsize", "racepctblack", "racePctWhite", "racePctAsian", "racePctHisp", "agePct12t21", "agePct12t29", "agePct16t24", "agePct65up", "numbUrban", "pctUrban", "medIncome", "pctWWage", "pctWFarmSelf", "pctWInvInc", "pctWSocSec", "pctWPubAsst", "pctWRetire", "medFamInc", "perCapInc", "whitePerCap", "blackPerCap", "indianPerCap", "AsianPerCap", "OtherPerCap", "HispPerCap", "NumUnderPov", "PctPopUnderPov", "PctLess9thGrade", "PctNotHSGrad", "PctBSorMore", "PctUnemployed", "PctEmploy", "PctEmplManu", "PctEmplProfServ", "PctOccupManu", "PctOccupMgmtProf", "MalePctDivorce", "MalePctNevMarr", "FemalePctDiv", "TotalPctDiv", "PersPerFam", "PctFam2Par", "PctKids2Par", "PctYoungKids2Par", "PctTeen2Par", "PctWorkMomYoungKids", "PctWorkMom", "NumIlleg", "PctIlleg", "NumImmig", "PctImmigRecent", "PctImmigRec5", "PctImmigRec8", "PctImmigRec10", "PctRecentImmig", "PctRecImmig5", "PctRecImmig8", "PctRecImmig10", "PctSpeakEnglOnly", "PctNotSpeakEnglWell", "PctLargHouseFam", "PctLargHouseOccup", "PersPerOccupHous", "PersPerOwnOccHous", "PersPerRentOccHous", "PctPersOwnOccup", "PctPersDenseHous", "PctHousLess3BR", "MedNumBR", "HousVacant", "PctHousOccup", "PctHousOwnOcc", "PctVacantBoarded", "PctVacMore6Mos", "MedYrHousBuilt", "PctHousNoPhone", "PctWOFullPlumb", "OwnOccLowQuart", "OwnOccMedVal", "OwnOccHiQuart", "RentLowQ", "RentMedian", "RentHighQ", "MedRent", "MedRentPctHousInc", "MedOwnCostPctInc", "MedOwnCostPctIncNoMtg", "NumInShelters", "NumStreet", "PctForeignBorn", "PctBornSameState", "PctSameHouse85", "PctSameCity85", "PctSameState85", "LemasSwornFT", "LemasSwFTPerPop", "LemasSwFTFieldOps", "LemasSwFTFieldPerPop", "LemasTotalReq", "LemasTotReqPerPop", "PolicReqPerOffic", "PolicPerPop", "RacialMatchCommPol", "PctPolicWhite", "PctPolicBlack", "PctPolicHisp", "PctPolicAsian", "PctPolicMinor", "OfficAssgnDrugUnits", "NumKindsDrugsSeiz", "PolicAveOTWorked", "LandArea", "PopDens", "PctUsePubTrans", "PolicCars", "PolicOperBudg", "LemasPctPolicOnPatr", "LemasGangUnitDeploy", "LemasPctOfficDrugUn", "PolicBudgPerPop", "ViolentCrimesPerPop")


# Replace 'column_names' with the list of column names you have
crime_data <- setNames(crime_data, column_names)

# Replace '?' with NA in the crime_data data frame
crime_data[crime_data == "?"] <- NA

# Calculate the percentage of missing values per column
na_percentage <- colMeans(is.na(crime_data))

# Identify columns with 50% or more missing values
columns_to_drop <- names(na_percentage[na_percentage >= 0.5])

# Drop the identified columns
crime_data_filtered <- crime_data[, !(names(crime_data) %in% columns_to_drop)]

# Convert all columns to numeric (excluding 'communityname' column, which is a string)
crime_data_filtered[, setdiff(seq_len(ncol(crime_data_filtered)), 4)] <- 
  apply(crime_data_filtered[, setdiff(seq_len(ncol(crime_data_filtered)), 4)], 2, as.numeric)

# Perform random imputation
mice_imputed_data <- mice(crime_data_filtered, method = "pmm", m = 1, maxit = 1)

# Extract the imputed data
crime_imputed_data <- complete(mice_imputed_data)

# Display the first few rows of the imputed data
head(crime_imputed_data)

# Subset the data frame to exclude the 'communityname' column
crime_data_subset_imputed <- crime_imputed_data[, -which(names(crime_imputed_data) == "communityname")]

# Select only numeric columns
crime_data_subset_imputed <- dplyr::select_if(crime_data_subset_imputed, is.numeric)

## Compute the correlation matrix
cor_matrix <- cor(crime_data_subset_imputed, use = "pairwise.complete.obs")

# Find the indices of highly correlated predictors
high_cor_indices <- findCorrelation(cor_matrix, cutoff = 0.6)

# Group highly correlated features together in a list of lists
cor_group <- list()
for (i in high_cor_indices) {
  group <- NULL
  for (j in high_cor_indices) {
    if (i != j) {
      cor_i_j <- cor_matrix[i, j]
      if (abs(cor_i_j) > 0.9) {
        if (is.null(group)) {
          group <- c(names(crime_data_subset_imputed)[i], names(crime_data_subset_imputed)[j])
        } else {
          group <- c(group, names(crime_data_subset_imputed)[j])
        }
      }
    }
  }
  if (!is.null(group)) {
    cor_group <- append(cor_group, list(group))
  }
}

# Print the list of highly correlated features
cat("Highly correlated features:\n")
print(cor_group)

# Initialize list to store indices of features to drop
features_to_drop <- list()
# Loop over each group of highly correlated features
for (i in 1:length(cor_group)) {
  group_vars <- cor_group[[i]]
  # Determine which feature to drop based on correlation with target variable
  cor_vals <- sapply(group_vars, function(x) cor(crime_data_subset_imputed[[x]], crime_data_subset_imputed$ViolentCrimesPerPop))
  max_corr <- max(abs(cor_vals))
  drop_index <- which(abs(cor_vals) < max_corr)
  print(drop_index)
  # Add the indices of the features to be dropped to the list
  features_to_drop[[i]] <- group_vars[drop_index]
}


# Flatten the list of features to drop
features_to_drop <- unlist(features_to_drop)

#remove repeats
features_to_drop<-unique(features_to_drop)
print(features_to_drop)

crime_data_subset_imputed_2 <- crime_data_subset_imputed[, !names(crime_data_subset_imputed) %in% features_to_drop]
# Compute the correlation matrix for the remaining columns
cor_matrix <- cor(crime_data_subset_imputed_2, use = "pairwise.complete.obs")

# Find the indices of highly correlated predictors
high_cor_indices <- findCorrelation(cor_matrix, cutoff = 0.7)

# Subset the correlation matrix to only include highly correlated features
cor_matrix_high_cor <- cor_matrix[high_cor_indices, high_cor_indices]

# Set plot size
png("correlation_plot.png", width = 1200, height = 1200,res = 150)

# Create a correlation plot matrix for the highly correlated features
corrplot(cor_matrix_high_cor, method = "color",
         col = colorRampPalette(c("#D73027", "#FC8D59", "#FEE090", "#FFFFBF", "#E0F3F8", "#91BFDB", "#4575B4"))(100),
         type = "lower",
         tl.col = "black",
         tl.srt = 45,
         tl.cex = 0.6,
         diag = FALSE,
         addCoef.col = "black",
         addCoefasPercent = TRUE,
         number.cex = 0.6)

# Save plot
dev.off()


```




```{r}
X=scale(crime_data_subset_imputed[,-103])

pr.out <- prcomp(X)
pr.out$rotation = -pr.out$rotation

pr.out$x = -pr.out$x
pca=pr.out$rotation %*% diag(pr.out$sdev)#factor loadings
pr.var <- pr.out$sdev^2 
pve <- pr.var/sum(pr.var) 
cumsum(pve)
# 12 pc is ok
png("Scree plot.png", width = 1200, height = 800,res = 150)
# Create a correlation plot matrix for the highly correlated features
par(mfrow = c(1, 2))
plot(pve[1:20], xlab = "Principal Component", ylab = "Proportion of
  Variance Explained", ylim = c(0, 1),pch=20,cex=0.8)
lines(x=c(1:20),y=pve[1:20],col='red')
plot(cumsum(pve)[1:20], xlab = "Principal Component", ylab = "Cumulative Proportion of Variance Explained", ylim = c(0, 1),pch=20,cex=0.8)
lines(x=c(1:20),y=cumsum(pve)[1:20],col='red')
dev.off()
Score=X %*% pr.out$rotation  
##loading see
library(reshape2)
##pca Score
XX=Score[,1:12]
head(XX)
```

```{r}
# png("pca_plot.png", width = 1200, height = 800,res = 150)
# Create a correlation plot matrix for the highly correlated features

load=pca[,1:12]
colnames(load)=paste0('PC',c(1:12))
load%>%  melt() %>% mutate(var=rep(rep(c(1,2),each=51),12)) %>% 
  ggplot(mapping = aes(x =Var2 , y = Var1, fill = value)) + 
  geom_tile() + scale_fill_gradient2(mid="white",low = 'blue', high = 'red') + theme(axis.text.y = element_text(size = 5),axis.text.x = element_text(size = 5))+
  xlab('components')+ylab('Var')+facet_wrap(~ var, scales = "free") 
# Save plot
# dev.off()
```



```{r}
mydata=cbind(XX,ViolentCrimesPerPop=crime_data_subset_imputed$ViolentCrimesPerPop)
# 3-10
train.control <- trainControl(method = "repeatedcv",number = 5, repeats = 1)
# train mod by pc
model <- train(ViolentCrimesPerPop~., data = mydata, method = "lm",
               trControl = train.control)
model
summary(model)
```

```{r}
png("top3pc_load.png", width = 1200, height = 200,res = 150)
# Create a correlation plot matrix for the highly correlated features
load[,1:3]%>%  melt()%>% filter(abs(value)>0.6) %>% 
  ggplot(mapping = aes(x =Var1 , y = Var2, fill = value)) + 
  geom_tile() + scale_fill_gradient2(mid="white",low = 'blue', high = 'red') + theme(text = element_text(size=8),,axis.text.y = element_text(size = 5),axis.text.x = element_text(angle=45,size = 3,hjust=1))+labs(title="The variables that the first three principal components mainly represent",y='components',x='correlated variable')
?
# Save plot
dev.off()

```

